export enum ApplicationPermissions {
    A_CRUD_SUPER = "A_CRUD_SUPER",
    A_CRUD_USERS = "A_CRUD_USERS",
    A_CRUD_ROLES = "A_CRUD_ROLES",
    A_CRUD_SERVICES = "A_CRUD_SERVICES",
    A_CRUD_BOOKINGS = "A_CRUD_BOOKINGS",
    A_CRUD_INDICATORS = "A_CRUD_INDICATORS",
    A_CRUD_ORDERS = "A_CRUD_ORDERS",
    AUTH_USER = "AUTH_USER",
}